services:
  - type: web
    name: examsense
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0